name: Build Resume Variants

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-resumes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Make build script executable
      run: chmod +x build-resume
    
    - name: Build all resume variants
      run: |
        ./build-resume full
        ./build-resume academic
        ./build-resume minimal
        ./build-resume industry
        ./build-resume tech
    
    - name: Upload resume artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-variants
        path: |
          *_resume/
        retention-days: 30
    
    - name: List generated files
      run: |
        echo "Generated resume variants:"
        find . -name "*_resume" -type d -exec echo "=== {} ===" \; -exec ls -la {} \;
